'use client'

import { cn } from '@/lib/utils'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import type { DataSource } from './types'

interface SourceConfig {
  label: string
  fullLabel: string
  color: string
  description: string
}

const SOURCE_CONFIG: Record<DataSource, SourceConfig> = {
  bgg: {
    label: 'BGG',
    fullLabel: 'BoardGameGeek',
    color: 'bg-orange-100 text-orange-700 border-orange-200',
    description: 'Imported from BoardGameGeek API',
  },
  wikidata: {
    label: 'WD',
    fullLabel: 'Wikidata',
    color: 'bg-blue-100 text-blue-700 border-blue-200',
    description: 'Enriched from Wikidata (CC0 licensed)',
  },
  wikipedia: {
    label: 'WP',
    fullLabel: 'Wikipedia',
    color: 'bg-violet-100 text-violet-700 border-violet-200',
    description: 'Extracted from Wikipedia article',
  },
  ai: {
    label: 'AI',
    fullLabel: 'AI Generated',
    color: 'bg-cyan-100 text-cyan-700 border-cyan-200',
    description: 'Generated by Claude AI from rulebook/sources',
  },
  manual: {
    label: 'Manual',
    fullLabel: 'Manual Entry',
    color: 'bg-slate-100 text-slate-700 border-slate-200',
    description: 'Manually entered by admin',
  },
  rulebook: {
    label: 'PDF',
    fullLabel: 'Rulebook PDF',
    color: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    description: 'Parsed from publisher rulebook PDF',
  },
}

const UNKNOWN_CONFIG: SourceConfig = {
  label: '?',
  fullLabel: 'Unknown',
  color: 'bg-gray-100 text-gray-500 border-gray-200',
  description: 'Source not tracked',
}

interface DataSourceBadgeProps {
  /** The data source identifier */
  source: string | null | undefined
  /** Size variant */
  size?: 'sm' | 'md'
  /** Show full label instead of abbreviation */
  showFullLabel?: boolean
  /** Show tooltip on hover */
  showTooltip?: boolean
  /** Additional CSS classes */
  className?: string
}

/**
 * DataSourceBadge displays a colored badge indicating the origin of data.
 * Used throughout Vecna pipeline to show data provenance.
 *
 * Sources:
 * - BGG (orange): BoardGameGeek import
 * - WD (blue): Wikidata enrichment
 * - WP (violet): Wikipedia extraction
 * - AI (cyan): Claude AI generated
 * - Manual (slate): Admin manual entry
 * - PDF (emerald): Rulebook PDF parsing
 */
export function DataSourceBadge({
  source,
  size = 'sm',
  showFullLabel = false,
  showTooltip = true,
  className,
}: DataSourceBadgeProps) {
  const config = SOURCE_CONFIG[source as DataSource] || UNKNOWN_CONFIG

  const sizeClasses = {
    sm: 'text-[10px] px-1.5 py-0.5',
    md: 'text-xs px-2 py-1',
  }

  const badge = (
    <span
      className={cn(
        'inline-flex items-center rounded border font-medium whitespace-nowrap',
        sizeClasses[size],
        config.color,
        className
      )}
    >
      {showFullLabel ? config.fullLabel : config.label}
    </span>
  )

  if (!showTooltip) {
    return badge
  }

  return (
    <TooltipProvider delayDuration={300}>
      <Tooltip>
        <TooltipTrigger asChild>{badge}</TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs">
          <p className="font-medium">{config.fullLabel}</p>
          <p className="text-xs text-muted-foreground">{config.description}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

/**
 * Get the configuration for a data source (useful for custom rendering)
 */
export function getSourceConfig(source: string | null | undefined): SourceConfig {
  return SOURCE_CONFIG[source as DataSource] || UNKNOWN_CONFIG
}

/**
 * Check if a string is a valid DataSource
 */
export function isValidDataSource(source: string | null | undefined): source is DataSource {
  return source !== null && source !== undefined && source in SOURCE_CONFIG
}
