'use client'

import { useCallback } from 'react'
import { generateSlug } from '@/lib/utils/slug'

export interface UseAutoSlugOptions {
  /** Whether this is a new item (always auto-generate slug) */
  isNew: boolean
  /** Current slug value */
  currentSlug: string
  /** Current name value (used to check if slug was auto-generated) */
  currentName: string
}

export interface UseAutoSlugReturn {
  /**
   * Handle name change with optional auto-slug generation.
   * Pass the update functions to modify both name and slug.
   */
  handleNameChange: (
    newName: string,
    updateName: (name: string) => void,
    updateSlug: (slug: string) => void
  ) => void
  /**
   * Generate a slug from a name string
   */
  generateSlugFromName: (name: string) => string
}

/**
 * Hook for auto-generating slugs from names.
 * Used in taxonomy, publisher, and family editors.
 *
 * Auto-generates slug when:
 * 1. Creating a new item (isNew = true)
 * 2. Current slug matches the auto-generated slug from current name
 *    (meaning user hasn't manually edited the slug)
 *
 * @example
 * ```tsx
 * const { handleNameChange } = useAutoSlug({
 *   isNew,
 *   currentSlug: item.slug,
 *   currentName: item.name
 * })
 *
 * const onNameChange = (name: string) => {
 *   handleNameChange(
 *     name,
 *     (name) => updateField('name', name),
 *     (slug) => updateField('slug', slug)
 *   )
 * }
 * ```
 */
export function useAutoSlug({
  isNew,
  currentSlug,
  currentName,
}: UseAutoSlugOptions): UseAutoSlugReturn {
  const generateSlugFromName = useCallback((name: string): string => {
    return generateSlug(name)
  }, [])

  const handleNameChange = useCallback(
    (
      newName: string,
      updateName: (name: string) => void,
      updateSlug: (slug: string) => void
    ) => {
      updateName(newName)

      // Auto-generate slug for new items or if slug matches old auto-generated slug
      const wasAutoGenerated = currentSlug === generateSlug(currentName)
      if (isNew || wasAutoGenerated) {
        updateSlug(generateSlug(newName))
      }
    },
    [isNew, currentSlug, currentName]
  )

  return {
    handleNameChange,
    generateSlugFromName,
  }
}
